version: '3.2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myUserPass
      MYSQL_DATABASE: mydb
      MYSQL_USER: myUser
      MYSQL_PASSWORD: myUser

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      PMA_Host: db
      MYSQL_ROOT_PASSWORD: myUserPass